package com.javapackage;

import java.util.Date;

public class Main {

    public static void main(String[] args) {
        System.out.println("Hello World");
        //right click class
        //open in terminal
        //javac Main.java
        //ls Main.class(generated bytecode file of the java class- stored in out file and can be run on any environment with a JRE) and Main.java

        //Executing java code

//        moleon@MacBook-Pro-4 javapackage % cd ..
//        moleon@MacBook-Pro-4 com % cd ..
//        moleon@MacBook-Pro-4 src % java com.javapackage.Main
//        Hello World
        //these are the compilation and execution steps we don't see when we are using Intellij

        //Variables
        int age = 30;
        int temperature = 20;
        age = 35;
         int myAge = 24;
         int herAge = myAge;
        System.out.println(herAge);

        //Primitive Types
        byte hisAge = 30;
        int viewsCount = 123_456_789; //just like we use commas in java we can add underscores to support readability
        System.out.println(viewsCount);
        long viewCount = 3_123_456_789L; // L or l is needed
        double price = 10.99;
        float totalPrice = 10.99f;
        char letter = 'A'; //single quote
        boolean isEligible = true;

        //Reference Types
        //use new to allocate memory
        Date now = new Date(); //now is a new instance of the Date class pre-written in Java
        System.out.println(now);
             now.getTime();    //the now instance can now use all the methods written within the Date class by using the "." reference
                    //. for i methods are pre-built in and are good time savers
    }
}
