package com.javapackage;

public class Main {

    public static void main(String[] args) {
        System.out.println("Hello World");
        //right click class
        //open in terminal
        //javac Main.java
        //ls Main.class(generated bytecode file of the java class- stored in out file and can be run on any environment with a JRE) and Main.java

        //Executing java code

//        moleon@MacBook-Pro-4 javapackage % cd ..
//        moleon@MacBook-Pro-4 com % cd ..
//        moleon@MacBook-Pro-4 src % java com.javapackage.Main
//        Hello World
        //these are the compilation and execution steps we don't see when we are using Intellij

    }
}
